general:
  app_name: telegram-controller
  default_debug_level: ${DEBUG_LEVEL}
  emit_enabled: True
  bpm_enabled: True
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: True
  kafka_log_handler_topic: logging
scheduler:
  db_keepalive_interval: 60
envoy:
  host: http://envoy:8080
camunda:
  engine_url: ${CAMUNDA_ENGINE_URL}
flask:
  default_port: ${API_CONTROLLER_PORT}
  debug_level: ERROR
  debug_enabled: False
kafka:
  enable_kafka_logging: False
  kafka_topic_prefix: ${TOPIC_PREFIX}
  debug_level: ${KAFKA_DEBUG_LEVEL}
  broker_url: ${BROKER_URL}
  auto_offset_reset: latest
  raw_messages_topic: telegram_raw_messages
telegram:
  api_id: ${TELEGRAM_API_ID}
  api_hash: ${TELEGRAM_API_HASH}
  string_session: ${TELEGRAM_GEN1_SESSION}
  request_retries: 50
  connection_retries: 999
  retry_delay: 10
  timeout: 1000
  watched_chats:
  - Albert III
  - Tommy Chartist📈
  - Miss Veronica Castro
  - Noah Lutz
  - HUSKY
  - Daniel Ramsey
  - Bit Obi-Wan
  - Y O K O
  - AlexClay - Trading Analyzes & Tips
  - MYC Signals
sqlalchemy:
  database_base_directory: /data
  db_url: mysql+mysqldb://pyeventsys:pyeventsys@mysql:3306/telegram-controller?charset=utf8mb4