general:
  app_name: binance-rest-controller
  default_debug_level: ${DEBUG_LEVEL}
  allow_duplicate_signals: False
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: True
  kafka_log_handler_topic: logging
scheduler:
  db_keepalive_interval: 60
envoy:
  host: http://envoy:8080
camunda:
  engine_url: ${CAMUNDA_ENGINE_URL}
binance:
  mock: False
  sandbox: False
  sandbox_apikey: ${BINANCE_S_APIKEY}
  sandbox_secret: ${BINANCE_S_SECRET}
  live_apikey: ${BINANCE_L_APIKEY}
  live_secret: ${BINANCE_L_SECRET}
  orders_allowed : True
flask:
  default_port: ${API_CONTROLLER_PORT}
  debug_level: ERROR
  debug_enabled: False
kafka:
  enable_kafka_logging: False
  kafka_topic_prefix: ${TOPIC_PREFIX}
  debug_level: ${KAFKA_DEBUG_LEVEL}
  broker_url: ${BROKER_URL}
  raw_messages_topic: pabs_raw_messages
  auto_offset_reset: latest
  signal_controller_consumer_group: binance_controller_group
  random_consumer_group: False
  signals_topic: signals
  binance_trade_data_topic: binance_trade_data
  binance_topic: binance
sqlalchemy:
  database_base_directory: /data
  db_url: mysql+mysqldb://pyeventsys:pyeventsys@mysql:3306/binance-rest-controller?charset=utf8mb4