general:
  app_name: pabs-signal-entry-worker
  default_debug_level: ${DEBUG_LEVEL}
  allow_duplicate_signals: True
  mock: True
  mock_state: "spot-buy-market"
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: True
  kafka_log_handler_topic: logging
envoy:
  host: http://envoy:8080
camunda:
  engine_url: ${CAMUNDA_ENGINE_URL}
flask:
  default_port: ${API_CONTROLLER_PORT}
  debug_level: ERROR
  debug_enabled: False
kafka:
  enable_kafka_logging: False
  kafka_topic_prefix: ${TOPIC_PREFIX}
  debug_level: ${KAFKA_DEBUG_LEVEL}
  broker_url: ${BROKER_URL}
  raw_messages_topic: pabs_raw_messages
  signal_controller_consumer_group: signal_worker_group
  auto_offset_reset: latest
  random_consumer_group: False
  signals_topic: signals
  binance_market_data_topic: binance_market_data
  binance_trade_data_topic: binance_trade_data
  binance_topic: binance
scheduler:
  work_poll_interval: 3
  funding_check_interval: 20
  db_keepalive_interval: 60
sqlalchemy:
  database_base_directory: /data
  db_url: mysql+mysqldb://pyeventsys:pyeventsys@mysql:3306/pabs-signal-entry-worker?charset=utf8mb4