version: '3'

networks:
  energysim:
    external:
      name: p_energysim

services:
  pabs-msg-from-file:
    build:
      context: ./pabs-msg-from-file
      dockerfile: Dockerfile
    container_name: pabs-msg-from-file
    image: pabs-msg-from-file:latest
    ports:
      - "8080"
    restart: unless-stopped
    networks:
      - energysim
    volumes:
      - ../pabs-msg-from-file/data:/data
    environment:
      - CROSSBAR_URL
      - CROSSBAR_REALM
      - DEBUG_LEVEL
      - API_CONTROLLER_PORT

  # camunda-test:
  #   build:
  #     context: ./camunda-test
  #     dockerfile: Dockerfile
  #   container_name: camunda-test
  #   image: camunda-test:latest
  #   ports:
  #     - "8080"
  #   restart: unless-stopped
  #   networks:
  #     - energysim
  #   volumes:
  #     - ./camunda-test/data:/data
  #   environment:
  #     - BROKER_URL
  #     - DEBUG_LEVEL
  #     - KAFKA_DEBUG_LEVEL
  #     - API_CONTROLLER_PORT
  #     - TOPIC_PREFIX
  #     - CAMUNDA_ENGINE_URL

  # event-pong:
  #   build:
  #     context: ./event-pong
  #     dockerfile: Dockerfile
  #   container_name: event-pong
  #   image: event-pong:latest
  #   ports:
  #     - "8080"
  #   restart: "no"
  #   networks:
  #     - energysim
  #   volumes:
  #     - 'event-pong_data:/data'
  #   environment:
  #     - BROKER_URL
  #     - DEBUG_LEVEL
  #     - KAFKA_DEBUG_LEVEL
  #     - API_CONTROLLER_PORT