version: '3'

networks:
  energysim:
    external:
      name: infra_energysim

services:
  sender:
    build:
      context: ./autobahn-sender
      dockerfile: Dockerfile
    container_name: sender
    image: sender
    ports:
      - "8086"
    restart: unless-stopped
    networks:
      - energysim
    # volumes:
    #   - ../pabs-msg-from-file/data:/data
    # environment:
    #   - CROSSBAR_URL
    #   - CROSSBAR_REALM
    #   - DEBUG_LEVEL
    #   - API_CONTROLLER_PORT

  receiver:
    build:
      context: ./autobahn-receiver
      dockerfile: Dockerfile
    container_name: receiver
    image: receiver
    ports:
      - "8087"
    restart: unless-stopped
    networks:
      - energysim
    # volumes:
    #   - ../pabs-msg-from-file/data:/data
    # environment:
    #   - CROSSBAR_URL
    #   - CROSSBAR_REALM
    #   - DEBUG_LEVEL
    #   - API_CONTROLLER_PORT

  receiver2:
    build:
      context: ./autobahn-receiver2
      dockerfile: Dockerfile
    container_name: receiver2
    image: receiver2
    ports:
      - "8088"
    restart: unless-stopped
    networks:
      - energysim
    # volumes:
    #   - ../pabs-msg-from-file/data:/data
    # environment:
    #   - CROSSBAR_URL
    #   - CROSSBAR_REALM
    #   - DEBUG_LEVEL
    #   - API_CONTROLLER_PORT

  # camunda-test:
  #   build:
  #     context: ./camunda-test
  #     dockerfile: Dockerfile
  #   container_name: camunda-test
  #   image: camunda-test:latest
  #   ports:
  #     - "8080"
  #   restart: unless-stopped
  #   networks:
  #     - energysim
  #   volumes:
  #     - ./camunda-test/data:/data
  #   environment:
  #     - BROKER_URL
  #     - DEBUG_LEVEL
  #     - KAFKA_DEBUG_LEVEL
  #     - API_CONTROLLER_PORT
  #     - TOPIC_PREFIX
  #     - CAMUNDA_ENGINE_URL

  # event-pong:
  #   build:
  #     context: ./event-pong
  #     dockerfile: Dockerfile
  #   container_name: event-pong
  #   image: event-pong:latest
  #   ports:
  #     - "8080"
  #   restart: "no"
  #   networks:
  #     - energysim
  #   volumes:
  #     - 'event-pong_data:/data'
  #   environment:
  #     - BROKER_URL
  #     - DEBUG_LEVEL
  #     - KAFKA_DEBUG_LEVEL
  #     - API_CONTROLLER_PORT