version: '3'

networks:
  energysim:
    external:
      name: infra_energysim

services:
  test:
    build:
      context: ./crossbar-twisted-test
      dockerfile: Dockerfile
    container_name: test
    image: test
    ports:
      - "8080"
    restart: unless-stopped
    networks:
      - energysim
    # volumes:
    #   - ../pabs-msg-from-file/data:/data
    # environment:
    #   - CROSSBAR_URL
    #   - CROSSBAR_REALM
    #   - DEBUG_LEVEL
    #   - API_CONTROLLER_PORT

  # camunda-test:
  #   build:
  #     context: ./camunda-test
  #     dockerfile: Dockerfile
  #   container_name: camunda-test
  #   image: camunda-test:latest
  #   ports:
  #     - "8080"
  #   restart: unless-stopped
  #   networks:
  #     - energysim
  #   volumes:
  #     - ./camunda-test/data:/data
  #   environment:
  #     - BROKER_URL
  #     - DEBUG_LEVEL
  #     - KAFKA_DEBUG_LEVEL
  #     - API_CONTROLLER_PORT
  #     - TOPIC_PREFIX
  #     - CAMUNDA_ENGINE_URL

  # event-pong:
  #   build:
  #     context: ./event-pong
  #     dockerfile: Dockerfile
  #   container_name: event-pong
  #   image: event-pong:latest
  #   ports:
  #     - "8080"
  #   restart: "no"
  #   networks:
  #     - energysim
  #   volumes:
  #     - 'event-pong_data:/data'
  #   environment:
  #     - BROKER_URL
  #     - DEBUG_LEVEL
  #     - KAFKA_DEBUG_LEVEL
  #     - API_CONTROLLER_PORT