apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: py-event-sys
spec:
  storageClassName: "managed-nfs-storage"
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany